// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repara_Ya__App.Data;

namespace Repara_Ya__App.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20201204180207_version1")]
    partial class version1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Repara_Ya__App.Models.Adquirir", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.ToTable("AdquirirTable");
                });

            modelBuilder.Entity("Repara_Ya__App.Models.IngresarAdquirir", b =>
                {
                    b.Property<string>("LoginID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.HasKey("LoginID");

                    b.ToTable("IngresarAdquirirTable");
                });

            modelBuilder.Entity("Repara_Ya__App.Models.IngresarOfrecer", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("IngresarOfrecerTable");
                });

            modelBuilder.Entity("Repara_Ya__App.Models.LoginAdquirir", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.ToTable("LoginAdquirirTable");
                });

            modelBuilder.Entity("Repara_Ya__App.Models.LoginOfrecer", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.ToTable("LoginOfrecerTable");
                });

            modelBuilder.Entity("Repara_Ya__App.Models.Ofrecer", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.ToTable("OfrecerTable");
                });

            modelBuilder.Entity("Repara_Ya__App.Models.QuieroAdquirirUnServicio", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.ToTable("QuieroAdquirirUnServicioTable");
                });

            modelBuilder.Entity("Repara_Ya__App.Models.QuieroOfrecerMisServicios", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.ToTable("QuieroOfrecerTable");
                });

            modelBuilder.Entity("Repara_Ya__App.Models.RegistrateAdquirir", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("longtext");

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<int>("Celular")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .HasColumnType("longtext");

                    b.Property<string>("Contraseña")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("RegistrateAdquirirTable");
                });

            modelBuilder.Entity("Repara_Ya__App.Models.RegistrateOfrecer", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("longtext");

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<int>("Celular")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("RegistrateOfrecerTable");
                });
#pragma warning restore 612, 618
        }
    }
}
